"""Add Solution Engine tables

Revision ID: add_solution_engine_tables
Revises: cf1caedb205b
Create Date: 2026-02-13

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'add_solution_engine_tables'
down_revision = 'cf1caedb205b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create blog_product_recommendations association table
    op.create_table('blog_product_recommendations',
        sa.Column('blog_id', sa.String(), nullable=True),
        sa.Column('product_id', sa.String(), nullable=True),
        sa.Column('recommendation_type', sa.String(length=50), nullable=True),
        sa.Column('match_score', sa.Float(), nullable=True),
        sa.Column('conversion_rate', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['blog_id'], ['blog_solutions.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    
    # Create blog_solutions table
    op.create_table('blog_solutions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('shopify_blog_id', sa.String(length=50), nullable=True),
        sa.Column('title', sa.String(length=300), nullable=True),
        sa.Column('handle', sa.String(length=200), nullable=True),
        sa.Column('blog_handle', sa.String(length=100), nullable=True),
        sa.Column('url', sa.String(length=500), nullable=True),
        sa.Column('content_type', sa.String(length=50), nullable=True),
        sa.Column('target_keywords', sa.JSON(), nullable=True),
        sa.Column('primary_fault_code', sa.String(length=20), nullable=True),
        sa.Column('related_fault_codes', sa.JSON(), nullable=True),
        sa.Column('applicable_transmissions', sa.JSON(), nullable=True),
        sa.Column('applicable_vehicles', sa.JSON(), nullable=True),
        sa.Column('faq_schema', sa.JSON(), nullable=True),
        sa.Column('howto_schema', sa.JSON(), nullable=True),
        sa.Column('authority_signals', sa.JSON(), nullable=True),
        sa.Column('monthly_clicks', sa.Integer(), nullable=True),
        sa.Column('monthly_impressions', sa.Integer(), nullable=True),
        sa.Column('avg_position', sa.Float(), nullable=True),
        sa.Column('avg_time_on_page', sa.Integer(), nullable=True),
        sa.Column('conversion_rate', sa.Float(), nullable=True),
        sa.Column('content_summary', sa.Text(), nullable=True),
        sa.Column('key_entities', sa.JSON(), nullable=True),
        sa.Column('difficulty_level', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['primary_fault_code'], ['fault_codes.code'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_solutions_primary_fault_code'), 'blog_solutions', ['primary_fault_code'], unique=False)
    op.create_index(op.f('ix_blog_solutions_shopify_blog_id'), 'blog_solutions', ['shopify_blog_id'], unique=False)
    
    # Create solution_paths table
    op.create_table('solution_paths',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('query_pattern', sa.String(length=200), nullable=True),
        sa.Column('query_intent', sa.String(length=50), nullable=True),
        sa.Column('steps', sa.JSON(), nullable=True),
        sa.Column('click_through_rate', sa.Float(), nullable=True),
        sa.Column('conversion_rate', sa.Float(), nullable=True),
        sa.Column('avg_revenue_per_path', sa.Float(), nullable=True),
        sa.Column('grok_optimized', sa.Boolean(), nullable=True),
        sa.Column('optimization_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_paths_query_pattern'), 'solution_paths', ['query_pattern'], unique=False)
    
    # Create product_recommendations table
    op.create_table('product_recommendations',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('context_type', sa.String(length=50), nullable=True),
        sa.Column('context_id', sa.String(length=100), nullable=True),
        sa.Column('recommendations', sa.JSON(), nullable=True),
        sa.Column('generated_by', sa.String(length=50), nullable=True),
        sa.Column('generation_prompt', sa.Text(), nullable=True),
        sa.Column('confidence_score', sa.Float(), nullable=True),
        sa.Column('impressions', sa.Integer(), nullable=True),
        sa.Column('clicks', sa.Integer(), nullable=True),
        sa.Column('purchases', sa.Integer(), nullable=True),
        sa.Column('revenue_generated', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create query_product_affinity table
    op.create_table('query_product_affinity',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('query_pattern', sa.String(length=200), nullable=True),
        sa.Column('product_id', sa.String(), nullable=True),
        sa.Column('impression_count', sa.Integer(), nullable=True),
        sa.Column('click_count', sa.Integer(), nullable=True),
        sa.Column('purchase_count', sa.Integer(), nullable=True),
        sa.Column('click_through_rate', sa.Float(), nullable=True),
        sa.Column('conversion_rate', sa.Float(), nullable=True),
        sa.Column('revenue_per_impression', sa.Float(), nullable=True),
        sa.Column('predicted_conversion_rate', sa.Float(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('query_pattern', 'product_id', name='unique_query_product')
    )
    op.create_index(op.f('ix_query_product_affinity_product_id'), 'query_product_affinity', ['product_id'], unique=False)
    op.create_index(op.f('ix_query_product_affinity_query_pattern'), 'query_product_affinity', ['query_pattern'], unique=False)
    
    # Create smart_snippets table
    op.create_table('smart_snippets',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('query', sa.String(length=300), nullable=True),
        sa.Column('query_variations', sa.JSON(), nullable=True),
        sa.Column('short_answer', sa.String(length=300), nullable=True),
        sa.Column('detailed_answer', sa.Text(), nullable=True),
        sa.Column('schema_type', sa.String(length=50), nullable=True),
        sa.Column('schema_json', sa.JSON(), nullable=True),
        sa.Column('related_products', sa.JSON(), nullable=True),
        sa.Column('ai_citation_count', sa.Integer(), nullable=True),
        sa.Column('position_0_count', sa.Integer(), nullable=True),
        sa.Column('authority_quote', sa.String(length=500), nullable=True),
        sa.Column('statistic_claims', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smart_snippets_query'), 'smart_snippets', ['query'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smart_snippets_query'), table_name='smart_snippets')
    op.drop_table('smart_snippets')
    op.drop_index(op.f('ix_query_product_affinity_query_pattern'), table_name='query_product_affinity')
    op.drop_index(op.f('ix_query_product_affinity_product_id'), table_name='query_product_affinity')
    op.drop_table('query_product_affinity')
    op.drop_table('product_recommendations')
    op.drop_index(op.f('ix_solution_paths_query_pattern'), table_name='solution_paths')
    op.drop_table('solution_paths')
    op.drop_index(op.f('ix_blog_solutions_shopify_blog_id'), table_name='blog_solutions')
    op.drop_index(op.f('ix_blog_solutions_primary_fault_code'), table_name='blog_solutions')
    op.drop_table('blog_solutions')
    op.drop_table('blog_product_recommendations')
    # ### end Alembic commands ###
