"""Add store intelligence tables

Revision ID: cf1caedb205b
Revises: 9175bbc98952
Create Date: 2026-02-11 14:38:12.029073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1caedb205b'
down_revision = '9175bbc98952'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection_optimizer', 'ga4_bounce_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('collection_optimizer', 'ga4_avg_engagement_time',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('collection_optimizer', 'ga4_conversion_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('collection_optimizer', 'ga4_revenue',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('collection_optimizer', 'baseline_ga4_revenue',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.drop_column('content_drafts', 'version')
    op.drop_column('content_drafts', 'generated_at')
    op.drop_column('content_drafts', 'published_at')
    op.drop_column('content_drafts', 'approved_at')
    op.drop_index(op.f('idx_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('idx_documents_source_type'), table_name='documents')
    op.drop_index(op.f('idx_generation_history_product_id'), table_name='generation_history')
    op.drop_index(op.f('idx_libraries_library_type'), table_name='libraries')
    op.alter_column('products', 'total_revenue',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'revenue_30d',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'revenue_90d',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'revenue_365d',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'revenue_all_time',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'transmission_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('products', 'product_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('products', 'vendor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.REAL(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('products', 'ga4_engagement_time',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'ga4_bounce_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'ga4_revenue',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'gsc_ctr',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'gsc_position',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'opportunity_level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'low'"))
    op.alter_column('products', 'last_analytics_sync',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    op.create_index(op.f('ix_products_total_sold'), 'products', ['total_sold'], unique=False)
    op.create_index(op.f('ix_products_transmission_code'), 'products', ['transmission_code'], unique=False)
    op.drop_index(op.f('idx_prompt_templates_template_type'), table_name='prompt_templates')
    op.alter_column('solutions', 'recommended_skus',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solutions', 'recommended_skus',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_prompt_templates_template_type'), 'prompt_templates', ['template_type'], unique=False)
    op.drop_index(op.f('ix_products_transmission_code'), table_name='products')
    op.drop_index(op.f('ix_products_total_sold'), table_name='products')
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.alter_column('products', 'last_analytics_sync',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('products', 'opportunity_level',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'low'"))
    op.alter_column('products', 'gsc_position',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'gsc_ctr',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'ga4_revenue',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'ga4_bounce_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'ga4_engagement_time',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'price',
               existing_type=sa.String(length=20),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('products', 'vendor',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'product_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'transmission_code',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'revenue_all_time',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'revenue_365d',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'revenue_90d',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'revenue_30d',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('products', 'total_revenue',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.create_index(op.f('idx_libraries_library_type'), 'libraries', ['library_type'], unique=False)
    op.create_index(op.f('idx_generation_history_product_id'), 'generation_history', ['product_id'], unique=False)
    op.create_index(op.f('idx_documents_source_type'), 'documents', ['source_type'], unique=False)
    op.create_index(op.f('idx_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.add_column('content_drafts', sa.Column('approved_at', sa.DATETIME(), nullable=True))
    op.add_column('content_drafts', sa.Column('published_at', sa.DATETIME(), nullable=True))
    op.add_column('content_drafts', sa.Column('generated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('content_drafts', sa.Column('version', sa.INTEGER(), nullable=True))
    op.alter_column('collection_optimizer', 'baseline_ga4_revenue',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('collection_optimizer', 'ga4_revenue',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('collection_optimizer', 'ga4_conversion_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('collection_optimizer', 'ga4_avg_engagement_time',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('collection_optimizer', 'ga4_bounce_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    # ### end Alembic commands ###
